#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Stage Two: 从医学文献中提取病例信息
"""

from .content_extractor import ContentExtractor
from .prompts import (
    CASE_SECTION_CONFIRMATION_TEMPLATE,
    CONTENT_ONLY_CASE_CONFIRMATION_TEMPLATE,
    STRICT_CASE_CONTENT_TEMPLATE,
    STRICT_DISCUSSION_CONTENT_TEMPLATE,
    CASE_INFO_EXTRACTION_TEMPLATE,
    DIAGNOSIS_EXTRACTION_TEMPLATE,
    TREATMENT_ITEMS_EXTRACTION_TEMPLATE,
    SECTION_TYPE_IDENTIFICATION_TEMPLATE
)

__all__ = [
    'ContentExtractor',
    'CASE_SECTION_CONFIRMATION_TEMPLATE',
    'CONTENT_ONLY_CASE_CONFIRMATION_TEMPLATE', 
    'STRICT_CASE_CONTENT_TEMPLATE',
    'STRICT_DISCUSSION_CONTENT_TEMPLATE',
    'CASE_INFO_EXTRACTION_TEMPLATE',
    'DIAGNOSIS_EXTRACTION_TEMPLATE',
    'TREATMENT_ITEMS_EXTRACTION_TEMPLATE',
    'SECTION_TYPE_IDENTIFICATION_TEMPLATE'
]
